### PR TITLE
Cull triangles that are entirely in front of the near plane

### PR DESCRIPTION
**Pull request by punkUser**

### CODE REVIEW

**Comment by jstewart-amd** [comment]
Hi @punkUser. Just so you know, we aren't ignoring this. @Anteru definitely wants to merge this change. We had to wait to get our contribution guidelines in order. Now that we have them, can you please respond back to say that you are okay with this part:

---

**IMPORTANT**: By creating a pull request, you agree to allow your contribution to be licensed by the project owners under the terms of the [MIT License](LICENSE.txt).

---

Thanks.

**Comment by punkUser** [comment]
@anteru explained what was going on last week - no issues :)

Yes I agree to the licensing terms.

**Comment by punkUser** [comment]
Do you need me to do something to get this merged here? I noticed you changed a bunch of whitespace stuff at some point and that may be creating conflicts?

**Comment by Anteru** [comment]
No, it's time. I'll merge when I get back into the office.
Am 23.03.2016 8:01 nachm. schrieb punkUser notifications@github.com:Do you need me to do something to get this merged here? I noticed you changed a bunch of whitespace stuff at some point and that may be creating conflicts?

**Comment by Anteru** [comment]
This has been merged and will be part of a future release - thanks again :)

**Pull request merged**
